[package]
name = "bitwarden_rs"
version = "1.0.0"
authors = ["Daniel García <dani-garcia@users.noreply.github.com>"]
edition = "2018"

repository = "https://github.com/dani-garcia/bitwarden_rs"
readme = "README.md"
license = "GPL-3.0-only"
publish = false
build = "build.rs"

[features]
default = ["enable_yubikey"]
enable_syslog = ["syslog", "fern/syslog-4"]
enable_yubikey = ["yubico"]

[dependencies]
# Web framework for nightly with a focus on ease-of-use, expressibility, and speed.
rocket = { version = "0.4.0", features = ["tls"], default-features = false }
rocket_contrib = "0.4.0"

# HTTP client
reqwest = "0.9.6"

# multipart/form-data support
multipart = "0.15.4"

# WebSockets library
ws = "0.7.9"

# MessagePack library
rmpv = "0.4.0"

# Concurrent hashmap implementation
chashmap = "2.2.0"

# A generic serialization/deserialization framework
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0.34"

# Logging
log = "0.4.6"
fern = "0.5.7"
syslog = { version = "4.0.1", optional = true }

# A safe, extensible ORM and Query builder
diesel = { version = "1.3.3", features = ["sqlite", "chrono", "r2d2"] }
diesel_migrations = { version = "1.3.0", features = ["sqlite"] }

# Bundled SQLite
libsqlite3-sys = { version = "0.9.3", features = ["bundled"] }

# Crypto library
ring = { version = "0.13.5", features = ["rsa_signing"] }

# UUID generation
uuid = { version = "0.7.1", features = ["v4"] }

# Date and time library for Rust
chrono = "0.4.6"

# TOTP library
oath = "0.10.2"

# Data encoding library
data-encoding = "2.1.2"

# JWT library
jsonwebtoken = "5.0.1"

# U2F library
u2f = "0.1.4"

# Yubico Library
yubico = { git = "https://github.com/uiri/yubico-rs", features = ["online"], default-features = false, optional = true }

# A `dotenv` implementation for Rust
dotenv = { version = "0.13.0", default-features = false }

# Lazy static macro
lazy_static = { version = "1.2.0", features = ["nightly"] }

# More derives
derive_more = "0.13.0"

# Numerical libraries
num-traits = "0.2.6"
num-derive = "0.2.3"

# Email libraries
lettre = "0.9.0"
lettre_email = "0.9.0"
native-tls = "0.2.2"

# Number encoding library
byteorder = "1.2.7"

[patch.crates-io]
# Add support for Timestamp type
rmp = { git = 'https://github.com/dani-garcia/msgpack-rust' }

# Use new native_tls version 0.2
lettre = { git = 'https://github.com/lettre/lettre', rev = 'c988b1760ad81' }
lettre_email = { git = 'https://github.com/lettre/lettre', rev = 'c988b1760ad81' }

# Allows optional libusb support
yubico = { git = 'https://github.com/dani-garcia/yubico-rs' }
